##------------------------------------------------------
## SAY SOME THING
##------------------------------------------------------
src_table_of = {	# matching table Dictionaries
	# DIM Tables					Source Tables
	'DIM_NhomDichVu'				:		'DM_NhomDichVu'			,													
	'DIM_DichVu'					:		'DM_DichVu'				,											
	'DIM_DonViTinh'					:		'DM_DonViTinh'			,												
	'DIM_LoaiVatTu'					:		'DM_LoaiVatTu'			,												
	'DIM_ICD'						:		'DM_ICD'				,										
	'DIM_Duoc'						:		'DM_Duoc'				,										
	'DIM_PhanNhomDuoc'				:		'DM_PhanNhomDuoc'		,														
	'DIM_LoaiDuoc'					:		'DM_LoaiDuoc'			,												
	'DIM_DonViHanhChinh'			:		'DM_DonViHanhChinh'		,															
	'DIM_BenhNhan'					:		'DM_BenhNhan'			,												
	'DIM_PhongBan'					:		'DM_PhongBan'			,												
	'DIM_GiuongBenh'				:		'DM_GiuongBenh'			,													
	'DIM_TienTe'					:		'DM_TienTe'				,											
	'DIM_LoaiGia'					:		'DM_LoaiGia'			,												
	'DIM_QuocGia'					:		'Lst_Dictionary'		,													
	'DIM_CongTy'					:		'DIM_KSK_CongTy'		,													
	'DIM_KhoDuoc'					:		'dm_khoduoc'			,												
	'DIM_NhaCungCap'				:		'DM_NhaCungCap'			,													
	'DIM_CoSoThuoc'					:		'DM_CoSoThuoc'			,												
	'DIM_DichVu_DonGia'				:		'DM_DichVu_DonGia'		,														
	'DIM_Duoc_DonGia'				:		'DM_Duoc_DonGia'		,														
	'DIM_KSK_BenhNhan'				:		'KSK_HopDong_BenhNhan'	,															
	'DIM_KSK_HopDong'				:		'KSK_HopDong'			,													
	'DIM_KSK_HopDong_DichVu'		:		'KSK_HopDong_DichVu'	,																	
	'DIM_NhanVien'					:		'NhanVien'				,											
	'DIM_NguonDuoc'					:		'DM_NguonDuoc'			,												
	'DIM_DuocKyTonKho'				:		'DuocKyTonKho'			,													
	'DIM_ThietBi'					:		'DM_ThietBi'			,												
	'DIM_BenhVien'					:		'DM_BenhVien'			,												
	'DIM_CheDoAnUong'				:		'Lst_Dictionary'		,														
	'DIM_CheDoChamSoc'				:		'Lst_Dictionary'		,														
	'DIM_LyDoTiepNhan'				:		'Lst_Dictionary'		,														
	'DIM_HinhThucDenKham'			:		'Lst_Dictionary'		,															
	'DIM_NgheNghiep'				:		'Lst_Dictionary'		,														
	'DIM_DanToc'					:		'Lst_Dictionary'		,													
	'DIM_HangSanXuat'				:		'DM_HangSanXuat'		,														
	'DIM_PhanLoaiKetQua'			:		'Lst_Dictionary'		,															
	'DIM_GiaiQuyetKhamBenh'			:		'Lst_Dictionary'		,															
	'DIM_LyDoNhapVien'				:		'Lst_Dictionary'		,														
	'DIM_LoaiBenhAn'				:		'Lst_Dictionary'		,														
	'DIM_KipMo_VaiTro'				:		'Lst_Dictionary'		,														
	'DIM_TienTe_TyGia'				:		'DM_TienTe_TyGia'		,														
	'DIM_DuocCoSoThuoc'				:		'DuocCoSoThuoc'			,
	# FACT Tables 					Source Tables 
	'FACT_TiepNhan'				:	'TiepNhan',
	#'FACT_CLSYeuCau'			:	'CLSYeuCau CLSKetQua',
	# 'FACT_CLSYeuCauChiTiet'		:	'CLSYeuCauChiTiet CLSKetQuaChiTiet',
	'FACT_KhamBenh'				:	'KhamBenh',
	'FACT_ToaThuoc'				:	'KhamBenh_ToaThuoc',
	# 'FACT_ToaThuocChiTiet'		:	'ToaThuoc NoiTru_ToaThuoc',
	'FACT_LichHen_BenhNhan'		:	'LichHen_BenhNhan',
	'FACT_HoaDon'				:	'HoaDon',
	'FACT_HoaDonChiTiet'		:	'HoaDonChiTiet',
	'FACT_ChungTu'				:	'ChungTu',
	'FACT_ChungTuChiTiet'		:	'ChungTuChiTiet',
	# 'FACT_BenhAn'				:	'BenhAn BenhAnNgoaiTru',
	'FACT_NoiTru'				:	'NoiTru_NhapVien',
	'FACT_NoiTruChiTiet'		:	'NoiTru_KhamBenh',
	'FACT_NoiTruLuuTru'			:	'NoiTru_LuuTru',
	'FACT_NoiTruDichVu'			:	'NoiTru_DichVu',
	'FACT_KSK_KhamBenh'			:	'KSK_HopDong_BenhNhan',
	'FACT_KSK_KhamBenhChiTiet'	:	'KSK_HopDong_BenhNhan_DichVu',
	'FACT_BenhAnPhauThuat'		:	'BenhAnPhauThuat',
	'FACT_BenhAnPhauThuat_Ekip'	:	'BenhAnPhauThuat_EKip',
	'FACT_DuocTonKho'			:	'DuocTonKho',
	'FACT_DuocTonDauKy'			:	'DuocTonDauKy',
	#'FACT_KhamGayMe'			:	'KhamGayMe_NguoiLon KhamGayMe_Tim KhamGayMe_TreEM',
	'XepLichMo'					:	'XepLichMo',
	'XepLichMo_EkipMo'			:	'XepLichMo_EkipMo'
}
