DIM_NhomDichVu=[
('NhomDichVu_Key',               None,               None,                None,                    None,                 None),
('NhomDichVu_Id',               'DM_NhomDichVu',               'NhomDichVu_Id',                None,                    None,                 None),
('MaNhomDichVu',               'DM_NhomDichVu',               'MaNhomDichVu',                None,                    None,                 None),
# ('LoaiDichVu_Id',               'DM_NhomDichVu',               'LoaiDichVu_Id',                None,                    None,                 None),
('TenNhomDichVu',               'DM_NhomDichVu',               'TenNhomDichVu',                None,                    None,                 None),
('TenNhomDichVu_En',               'DM_NhomDichVu',               'TenNhomDichVu_En',                None,                    None,                 None),
('TenNhomDichVu_Ru',               'DM_NhomDichVu',               'TenNhomDichVu_Ru',                None,                    None,                 None),
('Cap',               'DM_NhomDichVu',               'Cap',                None,                    None,                 None),
# ('CapTren_Key',               'DM_NhomDichVu',               'CapTren_Id',                'DIM_NhomDichVu',                    'NhomDichVu_Key',                 None),
('TraLoiKetQuaRieng',               'DM_NhomDichVu',               'TraLoiKetQuaRieng',                None,                    None,                 None),
('TamNgung',               'DM_NhomDichVu',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_NhomDichVu',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_NhomDichVu',               'NgayTao',                'DIM_Date',                    'Date_Key',                 None),
# ('NguoiTao_Id',               'DM_NhomDichVu',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_NhomDichVu',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 None),
# ('NguoiCapNhat_Id',               'DM_NhomDichVu',               'NguoiCapNhat_Id',                None,                    None,                 None),
('PrefixCode',               'DM_NhomDichVu',               'PrefixCode',                None,                    None,                 None),
]




DIM_DichVu=[
('DichVu_Key',               None,               None,                None,                    None,                 None),
('DichVu_Id',               'DM_DichVu',               'DichVu_Id',                None,                    None,                 None),
('NhomDichVu_Id',               'DM_DichVu',               'NhomDichVu_Id',                'DIM_NhomDichVu',                    'NhomDichVu_Key ',         'NhomDichVu_Id'),
('MaDichVu',               'DM_DichVu',               'MaDichVu',                None,                    None,                 None),
('MaDichVu_Seg01',               'DM_DichVu',               'MaDichVu_Seg01',                None,                    None,                 None),
('MaDichVu_Seg02',               'DM_DichVu',               'MaDichVu_Seg02',                None,                    None,                 None),
('MaDichVu_Seg03',               'DM_DichVu',               'MaDichVu_Seg03',                None,                    None,                 None),
('MaDichVu_Seg04',               'DM_DichVu',               'MaDichVu_Seg04',                None,                    None,                 None),
('TenDichVu',               'DM_DichVu',               'TenDichVu',                None,                    None,                 None),
('TenDichVu_En',               'DM_DichVu',               'TenDichVu_En',                None,                    None,                 None),
('TenDichVu_Ru',               'DM_DichVu',               'TenDichVu_Ru',                None,                    None,                 None),
('Cap',               'DM_DichVu',               'Cap',                'Cap',                    None,                 None),
# ('CapTren_Key',               'DM_DichVu',               'CapTren_Id',                'DIM_DichVu',                    'DIM_DichVu_Key',                 None),
('DonViTinh',               'DM_DichVu',               'DonViTinh',                None,                    None,                 None),
('Idx',               'DM_DichVu',               'Idx',                None,                    None,                 None),
('ChonHetCapDuoi',               'DM_DichVu',               'ChonHetCapDuoi',                None,                    None,                 None),
('CoGiaDichVu',               'DM_DichVu',               'CoGiaDichVu',                None,                    None,                 None),
('GiaCoDinh',               'DM_DichVu',               'GiaCoDinh',                None,                    None,                 None),
('ThucHienBenNgoai',               'DM_DichVu',               'ThucHienBenNgoai',                None,                    None,                 None),
('SoPhim',               'DM_DichVu',               'SoPhim',                None,                    None,                 None),
('MaQuiDinh',               'DM_DichVu',               'MaQuiDinh',                None,                    None,                 None),
('TamNgung',               'DM_DichVu',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_DichVu',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_DichVu',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_DichVu',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_DichVu',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_DichVu',               'NguoiCapNhat_Id',                None,                    None,                 None),
('CoGiaTriChuan',               'DM_DichVu',               'CoGiaTriChuan',                None,                    None,                 None),
('Test',               'DM_DichVu',               'Test',                None,                    None,                 None),
('Attribute1',               'DM_DichVu',               'Attribute1',                None,                    None,                 None),
('Attribute2',               'DM_DichVu',               'Attribute2',                None,                    None,                 None),
('Attribute3',               'DM_DichVu',               'Attribute3',                None,                    None,                 None),
('Attribute4',               'DM_DichVu',               'Attribute4',                None,                    None,                 None),
('Attribute5',               'DM_DichVu',               'Attribute5',                None,                    None,                 None),
# ('NhomDichVu_Report_Local_Id',               'DM_DichVu',               'NhomDichVu_Report_Local_Id',                None,                    None,                 None),
# ('NhomDichVu_Report_Global_Id',               'DM_DichVu',               'NhomDichVu_Report_Global_Id',                None,                    None,                 None),
# ('ShortName',               'DM_DichVu',               'ShortName',                None,                    None,                 None),
# ('InputCode',               'DM_DichVu',               'InputCode',                None,                    None,                 None),
# ('NoResult',               'DM_DichVu',               'NoResult',                None,                    None,                 None),
# ('ApplyFor',               'DM_DichVu',               'ApplyFor',                None,                    None,                 None),
# ('PrintWhenNull',               'DM_DichVu',               'PrintWhenNull',                None,                    None,                 None),
# ('ReportCode',               'DM_DichVu',               'ReportCode',                None,                    None,                 None),
# ('ReportTitle',               'DM_DichVu',               'ReportTitle',                None,                    None,                 None),
# ('DoUuTienDichVu',               'DM_DichVu',               'DoUuTienDichVu',                None,                    None,                 None),
# ('MaMay',               'DM_DichVu',               'MaMay',                None,                    None,                 None),
# ('BHYT',               'DM_DichVu',               'BHYT',                None,                    None,                 None),
# ('DacDiemDacBiet',               'DM_DichVu',               'DacDiemDacBiet',                None,                    None,                 None),
# ('HideGroup',               'DM_DichVu',               'HideGroup',                None,                    None,                 None),
# ('LoaiBenhPham_Id',               'DM_DichVu',               'LoaiBenhPham_Id',                None,                    None,                 None),
# ('STTDV',               'DM_DichVu',               'STTDV',                None,                    None,                 None),
]



DIM_DonViTinh=[
('DonViTinh_Key',               None,               None,                None,                    None,                 None),
('DonViTinh_Id',               'DM_DonViTinh',               'DonViTinh_Id',                None,                    None,                 None),
# ('LoaiVatTu_Key',               'DM_DonViTinh',               'LoaiVatTu_Id',                'DIM_LoaiVatTu',                    'LoaiVatTu_Key',                 None),
('MaDonViTinh',               'DM_DonViTinh',               'MaDonViTinh',                None,                    None,                 None),
('TenDonViTinh',               'DM_DonViTinh',               'TenDonViTinh',                None,                    None,                 None),
('DonViCoBan',               'DM_DonViTinh',               'DonViCoBan',                None,                    None,                 None),
('DonViCoBan_Id',               'DM_DonViTinh',               'DonViCoBan_Id',                None,                    None,                 None),
('GiaTriQuiDoi',               'DM_DonViTinh',               'GiaTriQuiDoi',                None,                    None,                 None),
('TenKhongDau',               'DM_DonViTinh',               'TenKhongDau',                None,                    None,                 None),
('TamNgung',               'DM_DonViTinh',               'TamNgung',                None,                    None,                 None),
('NgayTao_Key',               'DM_DonViTinh',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_DonViTinh',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_DonViTinh',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_DonViTinh',               'NguoiCapNhat_Id',                None,                    None,                 None),
('TenDonViTinh_En',               'DM_DonViTinh',               'TenDonViTinh_En',                None,                    None,                 None),
]


DIM_LoaiVatTu=[
('LoaiVatTu_Key',               None,               None,                None,                    None,                 None),
('LoaiVatTu_Key',               'DM_LoaiVatTu',               'LoaiVatTu_Id',                None,                    None,                 None),
('TenLoaiVatTu',               'DM_LoaiVatTu',               'TenLoaiVatTu',                None,                    None,                 None),
('TenLoaiVatTu_En',               'DM_LoaiVatTu',               'TenLoaiVatTu_En',                None,                    None,                 None),
('TenLoaiVatTu_Ru',               'DM_LoaiVatTu',               'TenLoaiVatTu_Ru',                None,                    None,                 None),
('TamNgung',               'DM_LoaiVatTu',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_LoaiVatTu',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_LoaiVatTu',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_LoaiVatTu',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_LoaiVatTu',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_LoaiVatTu',               'NguoiCapNhat_Id',                None,                    None,                 None),
('TinhVATVaoGiaVon',               'DM_LoaiVatTu',               'TinhVATVaoGiaVon',                None,                    None,                 None),
('TKHangTonKho',               'DM_LoaiVatTu',               'TKHangTonKho',                None,                    None,                 None),
('TKChiPhi',               'DM_LoaiVatTu',               'TKChiPhi',                None,                    None,                 None),
]


DIM_ICD=[
('ICD_Key',               None,               None,                None,                    None,                 None),
('ICD_Id',               'DM_ICD',               'ICD_Id',                None,                    None,                 None),
('MaICD',               'DM_ICD',               'MaICD',                None,                    None,                 None),
('TenICD',               'DM_ICD',               'TenICD',                None,                    None,                 None),
('TenICD_En',               'DM_ICD',               'TenICD_En',                None,                    None,                 None),
('TenICD_Ru',               'DM_ICD',               'TenICD_Ru',                None,                    None,                 None),
('MucICD',               'DM_ICD',               'MucICD',                None,                    None,                 None),
# ('ICD_Nhom_Id',               'DM_ICD',               'ICD_Nhom_Id',                None,                    None,                 None),
('PhanNhom',               'DM_ICD',               'PhanNhom',                None,                    None,                 None),
('Loai',               'DM_ICD',               'Loai',                None,                    None,                 None),
('BenhTruyenNhiem',               'DM_ICD',               'BenhTruyenNhiem',                None,                    None,                 None),
('TamNgung',               'DM_ICD',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_ICD',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_ICD',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_ICD',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_ICD',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_ICD',               'NguoiCapNhat_Id',                None,                    None,                 None),
# ('Ma',               'DM_ICD',               'Ma',                None,                    None,                 None),
# ('ChanDoanHinhAnh',               'DM_ICD',               'ChanDoanHinhAnh',                None,                    None,                 None),
]


DIM_Duoc=[
('Duoc_Key',               None,               None,                None,                    None,                 None),
('Duoc_Id',               'DM_Duoc',               'Duoc_Id',                None,                    None,                 None),
('MaDuoc',               'DM_Duoc',               'MaDuoc',                None,                    None,                 None),
('TenDuoc_Id',               'DM_Duoc',               'TenDuoc_Id',                None,                    None,                 None),
('DonViTinh_Key',               'DM_Duoc',               'DonViTinh_Id',                'DIM_DonViTinh',                    'DonViTinh_Key',                 'DonViTinh_Id'),
('HamLuong',               'DM_Duoc',               'HamLuong',                None,                    None,                 None),
('QuocGia_Key',               'DM_Duoc',               'QuocGia_Id',                'DIM_QuocGia',                    'QuocGia_Key',                 'QuocGia_Id'),
('HangSanXuat_Key',               'DM_Duoc',               'HangSanXuat_Id',                None,                    None,                 None),
('LoaiDuoc_Key',               'DM_Duoc',               'LoaiDuoc_Id',                'DIM_LoaiDuoc',                    'LoaiDuoc_Key',                 'LoaiDuoc_Id'),
('PhanNhomDuoc_Key',               'DM_Duoc',               'PhanNhomDuoc_Id',                'DIM_PhanNhomDuoc',                    'PhanNhomDuoc_Key',                 'PhanNhomDuoc_Id'),
('PhanLoaiDuoc',               'DM_Duoc',               'PhanLoaiDuoc',                None,                    None,                 None),
# ('DuongDung_Code',               'DM_Duoc',               'DuongDung_Id',                'Lst_Dictionary',                    'Dictionary_Code',                 None),
# ('DuongDung_Name',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name',                 None),
# ('DuongDung_Name_En',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name_En',                 None),
('BHYT',               'DM_Duoc',               'BHYT',                None,                    None,                 None),
('QuanTamDacBiet',               'DM_Duoc',               'QuanTamDacBiet',                None,                    None,                 None),
('CongDung',               'DM_Duoc',               'CongDung',                None,                    None,                 None),
('TamNgung',               'DM_Duoc',               'TamNgung',                None,                    None,                 None),
('NgayTao_Key',               'DM_Duoc',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_Duoc',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_Duoc',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_Duoc',               'NguoiCapNhat_Id',                None,                    None,                 None),
('MaKeToan',               'DM_Duoc',               'MaKeToan',                None,                    None,                 None),
('SoTaiKhoan',               'DM_Duoc',               'SoTaiKhoan',                None,                    None,                 None),
# ('SoThamChieu',               'DM_Duoc',               'SoThamChieu',                None,                    None,                 None),
# ('TamNgungDuTru',               'DM_Duoc',               'TamNgungDuTru',                None,                    None,                 None),
# ('TenHang',               'DM_Duoc',               'TenHang',                None,                    None,                 None),
# ('DonViTinh',               'DM_Duoc',               'DonViTinh',                None,                    None,                 None),
# ('HangSanXuat',               'DM_Duoc',               'HangSanXuat',                None,                    None,                 None),
# ('QuocGia',               'DM_Duoc',               'QuocGia',                None,                    None,                 None),
# ('TenDuocDayDu',               'DM_Duoc',               'TenDuocDayDu',                None,                    None,                 None),
# ('AutoCompleteField',               'DM_Duoc',               'AutoCompleteField',                None,                    None,                 None),
# ('TenHoatChat',               'DM_Duoc',               'TenHoatChat',                None,                    None,                 None),
# ('PhamVi',               'DM_Duoc',               'PhamVi',                None,                    None,                 None),
# ('HoatChat_Key',               'DM_Duoc',               'HoatChat_Id',                None,                    None,                 None),
# ('MaDuoc_1',               'DM_Duoc',               'MaDuoc_1',                None,                    None,                 None),
# ('MaDuoc_2',               'DM_Duoc',               'MaDuoc_2',                None,                    None,                 None),
# ('CachSuDung',               'DM_Duoc',               'CachSuDung',                None,                    None,                 None),
# ('HamLuongChiTiet',               'DM_Duoc',               'HamLuongChiTiet',                None,                    None,                 None),
# ('KhoQuanLy_Id',               'DM_Duoc',               'KhoQuanLy_Id',                None,                    None,                 None),
# ('Attribute_1',               'DM_Duoc',               'Attribute_1',                None,                    None,                 None),
# ('Attribute_2',               'DM_Duoc',               'Attribute_2',                None,                    None,                 None),
# ('Attribute_3',               'DM_Duoc',               'Attribute_3',                None,                    None,                 None),
# ('Attribute_4',               'DM_Duoc',               'Attribute_4',                None,                    None,                 None),
# ('HangKyGoi',               'DM_Duoc',               'HangKyGoi',                None,                    None,                 None),
# ('TinhTien',               'DM_Duoc',               'TinhTien',                None,                    None,                 None),
# ('Subgroup',               'DM_Duoc',               'Subgroup',                None,                    None,                 None),
# ('Sub_subgroup',               'DM_Duoc',               'Sub_subgroup',                None,                    None,                 None),
# ('MaDuocCIH',               'DM_Duoc',               'MaDuocCIH',                None,                    None,                 None),
# ('TacDungPhu',               'DM_Duoc',               'TacDungPhu',                None,                    None,                 None),
# ('MaDuocCIH_So',               'DM_Duoc',               'MaDuocCIH_So',                None,                    None,                 None),
# ('DonViDung_Id',               'DM_Duoc',               'DonViDung_Id',                None,                    None,                 None),
# ('TenBV',               'DM_Duoc',               'TenBV',                None,                    None,                 None),
# ('QLLo',               'DM_Duoc',               'QLLo',                None,                    None,                 None),
# ('Brandname',               'DM_Duoc',               'Brandname',                None,                    None,                 None),
# ('KeDon',               'DM_Duoc',               'KeDon',                None,                    None,                 None),
# ('ATC',               'DM_Duoc',               'ATC',                None,                    None,                 None),
# ('PT_BNTraTien',               'DM_Duoc',               'PT_BNTraTien',                None,                    None,                 None),
# ('Ven_Id',               'DM_Duoc',               'Ven_Id',                None,                    None,                 None),
# ('STTD',               'DM_Duoc',               'STTD',                None,                    None,                 None),
# ('MaNhom',               'DM_Duoc',               'MaNhom',                None,                    None,                 None),
# ('TenVTYT',               'DM_Duoc',               'TenVTYT',                None,                    None,                 None),
# ('VTYTDanTem',               'DM_Duoc',               'VTYTDanTem',                None,                    None,                 None),
# ('DinhMuc',               'DM_Duoc',               'DinhMuc',                None,                    None,                 None),
# ('DangBaoChe',               'DM_Duoc',               'DangBaoChe',                None,                    None,                 None),
# ('SoDangKy',               'DM_Duoc',               'SoDangKy',                None,                    None,                 None),
# ('MaHoatChat',               'DM_Duoc',               'MaHoatChat',                None,                    None,                 None),
# ('MaDuongDung',               'DM_Duoc',               'MaDuongDung',                None,                    None,                 None),
# ('VAT',               'DM_Duoc',               'VAT',                None,                    None,                 None),
# ('SoLuongDacBiet',               'DM_Duoc',               'SoLuongDacBiet',                None,                    None,                 None),
]


DIM_PhanNhomDuoc=[
('LoaiDuoc_Key',               None,               None,                None,                    None,                 None),
('PhanNhomDuoc_Id',               'DM_PhanNhomDuoc',               'PhanNhomDuoc_Id',                None,                    None,                 None),
('MaPhanNhomDuoc',               'DM_PhanNhomDuoc',               'MaPhanNhomDuoc',                None,                    None,                 None),
('TenPhanNhomDuoc',               'DM_PhanNhomDuoc',               'TenPhanNhomDuoc',                None,                    None,                 None),
('TenPhanNhomDuoc_En',               'DM_PhanNhomDuoc',               'TenPhanNhomDuoc_En',                None,                    None,                 None),
('TenPhanNhomDuoc_Ru',               'DM_PhanNhomDuoc',               'TenPhanNhomDuoc_Ru',                None,                    None,                 None),
# ('NhomDuoc_Key',               'DM_PhanNhomDuoc',               'NhomDuoc_Id',                'DM_NhomDuoc',                    'NhomDuoc_Id',                 None),
# ('MaNhomDuoc',               None,               None,                'DM_NhomDuoc',                    'MaNhomDuoc',                 None),
# ('TenNhomDuoc',               None,               None,                'DM_NhomDuoc',                    'TenNhomDuoc',                 None),
# ('TenNhomDuoc_En',               None,               None,                'DM_NhomDuoc',                    'TenNhomDuoc_En',                 None),
('TamNgung',               'DM_PhanNhomDuoc',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_PhanNhomDuoc',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_PhanNhomDuoc',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_PhanNhomDuoc',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_PhanNhomDuoc',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_PhanNhomDuoc',               'NguoiCapNhat_Id',                None,                    None,                 None),
]


DIM_LoaiDuoc=[
('LoaiDuoc_Key',               None,               None,                None,                    None,                 None),
('LoaiDuoc_Id',               'DM_LoaiDuoc',               'LoaiDuoc_Id',                None,                    None,                 None),
('MaLoaiDuoc',               'DM_LoaiDuoc',               'MaLoaiDuoc',                None,                    None,                 None),
('TenLoaiDuoc',               'DM_LoaiDuoc',               'TenLoaiDuoc',                None,                    None,                 None),
('TenLoaiDuoc_En',               'DM_LoaiDuoc',               'TenLoaiDuoc_En',                None,                    None,                 None),
('TenLoaiDuoc_Ru',               'DM_LoaiDuoc',               'TenLoaiDuoc_Ru',                None,                    None,                 None),
('LoaiVatTu_Id',               'DM_LoaiDuoc',               'LoaiVatTu_Id',                None,                    None,                 None),
# ('NhomLoaiDuoc_Key',               'DM_LoaiDuoc',               'NhomLoaiDuoc_Id',                None,                    None,                 None),
('QuanLyHanSuDung',               'DM_LoaiDuoc',               'QuanLyHanSuDung',                None,                    None,                 None),
('Idx',               'DM_LoaiDuoc',               'Idx',                None,                    None,                 None),
('TamNgung',               'DM_LoaiDuoc',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_LoaiDuoc',               'TenKhongDau',                None,                    None,                 None),
('NgayTao',               'DM_LoaiDuoc',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiTao_Id',               'DM_LoaiDuoc',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat',               'DM_LoaiDuoc',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiCapNhat_Id',               'DM_LoaiDuoc',               'NguoiCapNhat_Id',                None,                    None,                 None),
('TieuKhoanHangTonKho',               'DM_LoaiDuoc',               'TieuKhoanHangTonKho',                None,                    None,                 None),
('TieuKhoanChiPhi',               'DM_LoaiDuoc',               'TieuKhoanChiPhi',                None,                    None,                 None),
]



DIM_DonViHanhChinh=[
('DonViHanhChinh_Key',               'DM_DonViHanhChinh',               None,                None,                    None,                 None),
('DonViHanhChinh_Id',               'DM_DonViHanhChinh',               'DonViHanhChinh_Id',                None,                    None,                 None),
('MaDonVi',               'DM_DonViHanhChinh',               'MaDonVi',                None,                    None,                 None),
('TenDonVi',               'DM_DonViHanhChinh',               'TenDonVi',                None,                    None,                 None),
('CapDonVi',               'DM_DonViHanhChinh',               'CapDonVi',                None,                    None,                 None),
('CapTren_Id',               'DM_DonViHanhChinh',               'CapTren_Id',                None,                    None,                 None),
('MaVung_Id',               'DM_DonViHanhChinh',               'MaVung_Id',                None,                    None,                 None),
('KhuVucLuuTru_Id',               'DM_DonViHanhChinh',               'KhuVucLuuTru_Id',                None,                    None,                 None),
('TamNgung',               'DM_DonViHanhChinh',               'TamNgung',                None,                    None,                 None),
('TenTat',               'DM_DonViHanhChinh',               'TenTat',                None,                    None,                 None),
('TenTat_2',               'DM_DonViHanhChinh',               'TenTat_2',                None,                    None,                 None),
('TenTat_3',               'DM_DonViHanhChinh',               'TenTat_3',                None,                    None,                 None),
('TenKhongDau',               'DM_DonViHanhChinh',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_DonViHanhChinh',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_DonViHanhChinh',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_DonViHanhChinh',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_DonViHanhChinh',               'NguoiCapNhat_Id',                None,                    None,                 None),
]




DIM_BenhNhan=[
('BenhNhan_Key',               None,               None,                None,                    None,                 None),
('BenhNhan_Id',               'DM_BenhNhan',               'BenhNhan_Id',                None,                    None,                 None),
('MaYTe',               'DM_BenhNhan',               'MaYTe',                None,                    None,                 None),
('MaBenhVien',               'DM_BenhNhan',               'MaBenhVien',                None,                    None,                 None),
('SoVaoVien',               'DM_BenhNhan',               'SoVaoVien',                None,                    None,                 None),
('TenBenhNhan',               'DM_BenhNhan',               'TenBenhNhan',                None,                    None,                 None),
('Ho',               'DM_BenhNhan',               'Ho',                None,                    None,                 None),
('Ten',               'DM_BenhNhan',               'Ten',                None,                    None,                 None),
('GioiTinh',               'DM_BenhNhan',               'GioiTinh',                None,                    None,                 None),
# ('NgaySinh_Key',               'DM_BenhNhan',               'NgaySinh',                'DIM_Date',                    'Date_Key',                 None),
('NamSinh',               'DM_BenhNhan',               'NamSinh',                None,                    None,                 None),
('SoNha',               'DM_BenhNhan',               'SoNha',                None,                    None,                 None),
('DiaChi',               'DM_BenhNhan',               'DiaChi',                None,                    None,                 None),
# ('NhomMau',               'DM_BenhNhan',               'NhomMau_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'NhomMau_Id'),
# ('YeuToRh',               'DM_BenhNhan',               'YeuToRh_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'YeuToRh_Id'),
('TienSuDiUng',               'DM_BenhNhan',               'TienSuDiUng',                None,                    None,                 None),
('SoLuuTruNgoaiTru',               'DM_BenhNhan',               'SoLuuTruNgoaiTru',                None,                    None,                 None),
('SoLuuTruNoiTru',               'DM_BenhNhan',               'SoLuuTruNoiTru',                None,                    None,                 None),
('QuocTich_Key',               'DM_BenhNhan',               'QuocTich_Id',                'DIM_QuocGia',                    'QuocGia_Key',                 'QuocGia_Id'),
# ('DonViHanhChinh_Key',               'DM_BenhNhan',               'TinhThanh_Id',                'DIM_DonViHanhChinh',                    'DonViHanhChinh_Key',                 None),
# ('DanToc_Key',               'DM_BenhNhan',               'DanToc_Id',                'DIM_DanToc',                    'DanToc_Key',                 None),
# ('NgheNghiep_Key',               'DM_BenhNhan',               'NgheNghiep_Id',                'DIM_NgheNghiep',                    'NgheNghiep_Key',                 None),
('VietKieu',               'DM_BenhNhan',               'VietKieu',                None,                    None,                 None),
('NguoiNuocNgoai',               'DM_BenhNhan',               'NguoiNuocNgoai',                None,                    None,                 None),
('CMND',               'DM_BenhNhan',               'CMND',                None,                    None,                 None),
('HoChieu',               'DM_BenhNhan',               'HoChieu',                None,                    None,                 None),
('TenKhongDau',               'DM_BenhNhan',               'TenKhongDau',                None,                    None,                 None),
('GhiChu',               'DM_BenhNhan',               'GhiChu',                None,                    None,                 None),
# ('NgayTao_Key',               'DM_BenhNhan',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_BenhNhan',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_BenhNhan',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_BenhNhan',               'NguoiCapNhat_Id',                None,                    None,                 None),
# ('NgayCapThe_Key',               'DM_BenhNhan',               'NgayCapThe',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NamCapThe',               'DM_BenhNhan',               'NamCapThe',                None,                    None,                 None),
# ('ThoiGianCapThe_Key',               'DM_BenhNhan',               'ThoiGianCapThe',                'DIM_Time',                    'Time_Key',                 None),
('NhanVien_Key',               'DM_BenhNhan',               'NhanVien_Id',                'DIM_NhanVien',                    'NhanVien_Key',                 'NhanVien_Id'),
('TienSuBenh',               'DM_BenhNhan',               'TienSuBenh',                None,                    None,                 None),
# ('TienSuHutThuocLa',               'DM_BenhNhan',               'TienSuHutThuocLa',                None,                    None,                 None),
# ('DonViCongTac_Id',               'DM_BenhNhan',               'DonViCongTac_Id',                None,                    None,                 None),
# ('SoDienThoai',               'DM_BenhNhan',               'SoDienThoai',                None,                    None,                 None),
# ('DiaChiThuongTru',               'DM_BenhNhan',               'DiaChiThuongTru',                None,                    None,                 None),
# ('DiaChiLienLac',               'DM_BenhNhan',               'DiaChiLienLac',                None,                    None,                 None),
# ('Email',               'DM_BenhNhan',               'Email',                None,                    None,                 None),
# ('DiaChiCoQuan',               'DM_BenhNhan',               'DiaChiCoQuan',                None,                    None,                 None),
# ('TuVong',               'DM_BenhNhan',               'TuVong',                None,                    None,                 None),
# ('NgayTuVong_Key',               'DM_BenhNhan',               'NgayTuVong',                None,                    None,                 None),
# ('ThoiGianTuVong',               'DM_BenhNhan',               'ThoiGianTuVong',                None,                    None,                 None),
# ('NguyenNhanTuVong_Id',               'DM_BenhNhan',               'NguyenNhanTuVong_Id',                None,                    None,                 None),
# ('NguoiGhiNhanTuVong_Id',               'DM_BenhNhan',               'NguoiGhiNhanTuVong_Id',                None,                    None,                 None),
# ('ThoiGianGhiNhanTuVong_Key',               'DM_BenhNhan',               'ThoiGianGhiNhanTuVong',                None,                    None,                 None),
# ('CountNotes',               'DM_BenhNhan',               'CountNotes',                None,                    None,                 None),
# ('NgayTaoBenhNhan_Key',               'DM_BenhNhan',               'NgayTaoBenhNhan',                'DIM_Date',                    'Date_Key',                 None),
# ('TienCan',               'DM_BenhNhan',               'TienCan',                None,                    None,                 None),
# ('BenhManTinh',               'DM_BenhNhan',               'BenhManTinh',                None,                    None,                 None),
# ('BenhDiTruyen',               'DM_BenhNhan',               'BenhDiTruyen',                None,                    None,                 None),
# ('ChiDinhDacBiet',               'DM_BenhNhan',               'ChiDinhDacBiet',                None,                    None,                 None),
('MoiQuanHe',               'DM_BenhNhan',               'MoiQuanHe_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'MoiQuanHe_Id'),
# ('DiaChi_NLH',               'DM_BenhNhan',               'DiaChi_NLH',                None,                    None,                 None),
# ('DienThoai_NLH',               'DM_BenhNhan',               'DienThoai_NLH',                None,                    None,                 None),
# ('NguoiLienHe_Id',               'DM_BenhNhan',               'NguoiLienHe_Id',                None,                    None,                 None),
# ('NguoiLienHe',               'DM_BenhNhan',               'NguoiLienHe',                None,                    None,                 None),
# ('TinhTrangHonNhan_Id',               'DM_BenhNhan',               'TinhTrangHonNhan_Id',                None,                    None,                 None),
# ('DienThoaiBan',               'DM_BenhNhan',               'DienThoaiBan',                None,                    None,                 None),
# ('NgayHetHan_Passport_Key',               'DM_BenhNhan',               'NgayHetHan_Passport',                'DIM_Date',                    'Date_Key',                 None),
# ('CTBH_1',               'DM_BenhNhan',               'CTBH_1',                None,                    None,                 None),
# ('CTBH_2',               'DM_BenhNhan',               'CTBH_2',                None,                    None,                 None),
# ('CTBH_3',               'DM_BenhNhan',               'CTBH_3',                None,                    None,                 None),
# ('HoTruocTen',               'DM_BenhNhan',               'HoTruocTen',                None,                    None,                 None),
# ('NgayCapCMND',               'DM_BenhNhan',               'NgayCapCMND',                None,                    None,                 None),
# ('NoiCapCMND',               'DM_BenhNhan',               'NoiCapCMND',                None,                    None,                 None),
# ('GoiPACS',               'DM_BenhNhan',               'GoiPACS',                None,                    None,                 None),
# ('PIDPACS',               'DM_BenhNhan',               'PIDPACS',                None,                    None,                 None),
# ('ThuocLa',               'DM_BenhNhan',               'ThuocLa',                None,                    None,                 None),
# ('VanDong',               'DM_BenhNhan',               'VanDong',                None,                    None,                 None),
# ('Ruou',               'DM_BenhNhan',               'Ruou',                None,                    None,                 None),
# ('CaPhe',               'DM_BenhNhan',               'CaPhe',                None,                    None,                 None),
# ('Tra',               'DM_BenhNhan',               'Tra',                None,                    None,                 None),
# ('ThuocDangDung',               'DM_BenhNhan',               'ThuocDangDung',                None,                    None,                 None),
# ('DCTamTru',               'DM_BenhNhan',               'DCTamTru',                None,                    None,                 None),
('QuocGia_Key',               'DM_BenhNhan',               'QuocGia_Id',                'DIM_QuocGia',                    'QuocGia_Key',                 'QuocGia_Id'),
# ('BenhNhanCu_Id',               'DM_BenhNhan',               'BenhNhanCu_Id',                None,                    None,                 None),
]


DIM_PhongBan=[
('PhongBan_Key',               None,               None,                None,                    None,                 None),
('PhongBan_Id',               'DM_PhongBan',               'PhongBan_Id',                None,                    None,                 None),
('MaPhongBan',               'DM_PhongBan',               'MaPhongBan',                None,                    None,                 None),
('TenPhongBan',               'DM_PhongBan',               'TenPhongBan',                None,                    None,                 None),
('TenPhongBan_En',               'DM_PhongBan',               'TenPhongBan_En',                None,                    None,                 None),
('TenPhongBan_Ru',               'DM_PhongBan',               'TenPhongBan_Ru',                None,                    None,                 None),
('LoaiPhongBan_Id',               'DM_PhongBan',               'LoaiPhongBan_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'LoaiPhongBan_Id'),
# ('LoaiPhongBan_Code',               None,               None,                'Lst_Dictionary',                    'Dictionary_Code',                 None),
# ('LoaiPhongBan_Name',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name',                 None),
# ('LoaiPhongBan_Name_En',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name_En',                 None),
('Cap',               'DM_PhongBan',               'Cap',                None,                    None,                 None),
# ('CapTren_Key',               'DM_PhongBan',               'CapTren_Id',                'DIM_PhongBan',                    'CapTren_Key',                 None),
('TruongPhong_Key',               'DM_PhongBan',               'TruongPhong',                'DIM_NhanVien',                    'NhanVien_Key',                 None),
('LoaiPhongBenh_Id',               'DM_PhongBan',               'LoaiPhongBenh_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 None),
# ('LoaiPhongBenh_Code',               None,               None,                'Lst_Dictionary',                    'Dictionary_Code',                 None),
# ('LoaiPhongBenh_Name',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name',                 None),
# ('LoaiPhongBenh_Name_En',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name_En',                 None),
('TamNgung',               'DM_PhongBan',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_PhongBan',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_PhongBan',               'NgayTao',                'DIM_Date',                    'Date_Key',                'Ngay'),
# ('NguoiTao_Id',               'DM_PhongBan',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_PhongBan',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_PhongBan',               'NguoiCapNhat_Id',                None,                    None,                 None),
# ('CoThucHienDichVu',               'DM_PhongBan',               'CoThucHienDichVu',                None,                    None,                 None),
# ('Idx',               'DM_PhongBan',               'Idx',                None,                    None,                 None),
# ('QuanLyNhanSu',               'DM_PhongBan',               'QuanLyNhanSu',                None,                    None,                 None),
# ('IsKhoaDieuTri',               'DM_PhongBan',               'IsKhoaDieuTri',                None,                    None,                 None),
# ('IsChuyenKhoa',               'DM_PhongBan',               'IsChuyenKhoa',                None,                    None,                 None),
# ('CostCenTer_Id',               'DM_PhongBan',               'CostCenTer_Id',                None,                    None,                 None),
# ('ChuyenKhoa_Key',               'DM_PhongBan',               'ChuyenKhoa_Id',                None,                    None,                 None),
# ('Tang',               'DM_PhongBan',               'Tang',                None,                    None,                 None),
]


DIM_GiuongBenh=[
('GiuongBenh_Key',               None,               None,                None,                    None,                 None),
('GiuongBenh_Id',               'DM_GiuongBenh',               'GiuongBenh_Id',                None,                    None,                 None),
('MaGiuong',               'DM_GiuongBenh',               'MaGiuong',                None,                    None,                 None),
# ('KhoaDieuTri_Key',               'DM_GiuongBenh',               'KhoaDieuTri_Id',                'DIM_PhongBan',                    'PhongBan_Key',                 None),
# ('PhongBenh_Id',               'DM_GiuongBenh',               'PhongBenh_Id',                None,                    None,                 None),
('Tang',               'DM_GiuongBenh',               'Tang',                None,                    None,                 None),
('GiuongTrong',               'DM_GiuongBenh',               'GiuongTrong',                None,                    None,                 None),
('TamNgung',               'DM_GiuongBenh',               'TamNgung',                None,                    None,                 None),
('MoTa',               'DM_GiuongBenh',               'MoTa',                None,                    None,                 None),
('VatDungKemTheo',               'DM_GiuongBenh',               'VatDungKemTheo',                None,                    None,                 None),
('NgayTao_Key',               'DM_GiuongBenh',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiTao_Id',               'DM_GiuongBenh',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_GiuongBenh',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiCapNhat_Id',               'DM_GiuongBenh',               'NguoiCapNhat_Id',                None,                    None,                 None),
# ('TrangThai_Key',               'DM_GiuongBenh',               'TrangThai_Id',                None,                    None,                 None),
('DungChung',               'DM_GiuongBenh',               'DungChung',                None,                    None,                 None),
# ('DichVuKhachHang_Id',               'DM_GiuongBenh',               'DichVuKhachHang_Id',                None,                    None,                 None),
# ('DichVuChamSoc_Id',               'DM_GiuongBenh',               'DichVuChamSoc_Id',                None,                    None,                 None),
# ('MaGiuongBHYT',               'DM_GiuongBenh',               'MaGiuongBHYT',                None,                    None,                 None),
]


DIM_TienTe=[
('TienTe_Key',               None,               None,                None,                    None,                 None),
('TienTe_Id',               'DM_TienTe',               'TienTe_Id',                None,                    None,                 None),
('TenTienTe',               'DM_TienTe',               'TenTienTe',                None,                    None,                 None),
('TenTienTe_En',               'DM_TienTe',               'TenTienTe_En',                None,                    None,                 None),
('TamNgung',               'DM_TienTe',               'TamNgung',                None,                    None,                 None),
('NgayTao_Key',               'DM_TienTe',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_TienTe',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_TienTe',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'DM_TienTe',               'NguoiCapNhat_Id',                None,                    None,                 None),
]



DIM_LoaiGia=[
('LoaiGia_Key',               None,               None,                None,                    None,                 None),
('LoaiGia_Id',               'DM_LoaiGia',               'LoaiGia_Id',                None,                    None,                 None),
('MaLoaiGia',               'DM_LoaiGia',               'MaLoaiGia',                None,                    None,                 None),
('TenLoaiGia',               'DM_LoaiGia',               'TenLoaiGia',                None,                    None,                 None),
('TenLoaiGia_EN',               'DM_LoaiGia',               'TenLoaiGia_EN',                None,                    None,                 None),
('NhomGia_Id',               'DM_LoaiGia',               'NhomGia_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'NhomGia_Id'),
# ('NhomGia_Code',               None,               None,                'Lst_Dictionary',                    'Dictionary_Code',                 None),
# ('NhomGia_Name',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name',                 None),
# ('NhomGia_Name_En',               None,               None,                'Lst_Dictionary',                    'Dictionary_Name_En',                 None),
# ('CapTren_Id',               'DM_LoaiGia',               'CapTren_Id',                None,                    None,                 None),
('GhiChu',               'DM_LoaiGia',               'GhiChu',                None,                    None,                 None),
('TamNgung',               'DM_LoaiGia',               'TamNgung',                None,                    None,                 None),
('NgayTao_Key',               'DM_LoaiGia',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'DM_LoaiGia',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_LoaiGia',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiCapNhat_Id',               None,               'NguoiCapNhat_Id',                None,                    None,                 None),
# ('Idx',               None,               'Idx',                None,                    None,                 None),
]



DIM_QuocGia=[
('QuocGia_Key',               None,               None,                None,                    None,                 None),
('QuocGia_Id',               'Lst_Dictionary',               'Dictionary_Id',                None,                    None,                 None),
('QuocGia_Code',               'Lst_Dictionary',               'Dictionary_Code',                None,                    None,                 None),
('QuocGia_Name',               'Lst_Dictionary',               'Dictionary_Name',                None,                    None,                 None),
('QuocGia_Name_En',               'Lst_Dictionary',               'Dictionary_Name_En',                None,                    None,                 None),
('QuocGia_Name_Ru',               'Lst_Dictionary',               'Dictionary_Name_Ru',                None,                    None,                 None),
('Latin_Name',               'Lst_Dictionary',               'Latin_Name',                None,                    None,                 None),
('NgayTao_Key',               'Lst_Dictionary',               'Creation_Date',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'Lst_Dictionary',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'Lst_Dictionary',               'Last_Update_Date',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'Lst_Dictionary',               'NguoiCapNhat_Id',                None,                    None,                 None),
]


DIM_CongTy=[
('Congty_Key',               None,               None,                None,                    None,                 None),
('Congty_Id',               'KSK_CongTy',               'Congty_Id',                None,                    None,                 None),
('MaCongty',               'KSK_CongTy',               'MaCongty',                None,                    None,                 None),
('TenCongty',               'KSK_CongTy',               'TenCongty',                None,                    None,                 None),
('TenCongty_En',               'KSK_CongTy',               'TenCongty_En',                None,                    None,                 None),
('TenCongty_Ru',               'KSK_CongTy',               'TenCongty_Ru',                None,                    None,                 None),
('DiaChi',               'KSK_CongTy',               'DiaChi',                None,                    None,                 None),
('DienThoai',               'KSK_CongTy',               'DienThoai',                None,                    None,                 None),
('Fax',               'KSK_CongTy',               'Fax',                None,                    None,                 None),
('Email',               'KSK_CongTy',               'Email',                None,                    None,                 None),
('MaSoThue',               'KSK_CongTy',               'MaSoThue',                None,                    None,                 None),
('GiamDoc',               'KSK_CongTy',               'GiamDoc',                None,                    None,                 None),
('NguoiLienHe',               'KSK_CongTy',               'NguoiLienHe',                None,                    None,                 None),
('NuocNgoai',               'KSK_CongTy',               'NuocNgoai',                None,                    None,                 None),
('NhaNuoc',               'KSK_CongTy',               'NhaNuoc',                None,                    None,                 None),
('TamNgung',               'KSK_CongTy',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'KSK_CongTy',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'KSK_CongTy',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiTao_Id',               'KSK_CongTy',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'KSK_CongTy',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
# ('NguoiCapNhat_Id',               'KSK_CongTy',               'NguoiCapNhat_Id',                None,                    None,                 None),
('HeSo',               'KSK_CongTy',               'HeSo',                None,                    None,                 None),
('DienThoai_LH',               'KSK_CongTy',               'DienThoai_LH',                None,                    None,                 None),
('NguoiLienHe2',               'KSK_CongTy',               'NguoiLienHe2',                None,                    None,                 None),
('DienThoai_LH2',               'KSK_CongTy',               'DienThoai_LH2',                None,                    None,                 None),
]



DIM_KhoDuoc=[
('KhoDuoc_Key',               None,               None,                None,                    None,                 None),
('KhoDuoc_Id',               'dm_khoduoc',               'KhoDuoc_Id',                None,                    None,                 None),
('MaKho',               'dm_khoduoc',               'MaKho',                None,                    None,                 None),
('TenKho',               'dm_khoduoc',               'TenKho',                None,                    None,                 None),
('PhongBan_Key',               'dm_khoduoc',               'PhongBan_Id',                'DIM_PhongBan',                    'PhongBan_Key',                 'PhongBan_Id'),
# ('LoaiKho',               'dm_khoduoc',               'LoaiKho_Id',                'Lst_Dictionary',                    'Dictionary_Id',                 'LoaiKho_Id'),
('TamNgung',               'dm_khoduoc',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'dm_khoduoc',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'dm_khoduoc',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Date'),
('NguoiTao_Id',               'dm_khoduoc',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'dm_khoduoc',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Date'),
('NguoiCapNhat_Id',               'dm_khoduoc',               'NguoiCapNhat_Id',                None,                    None,                 None),
('QLNguon',               'dm_khoduoc',               'QLNguon',                None,                    None,                 None),
('KhoDuoc',               'dm_khoduoc',               'KhoDuoc',                None,                    None,                 None),
('KhoTaiSan',               'dm_khoduoc',               'KhoTaiSan',                None,                    None,                 None),
('KhoNHM',               'dm_khoduoc',               'KhoNHM',                None,                    None,                 None),
('KhoVPP',               'dm_khoduoc',               'KhoVPP',                None,                    None,                 None),
('KhoTTB',               'dm_khoduoc',               'KhoTTB',                None,                    None,                 None),
('TenKho_EN',               'dm_khoduoc',               'TenKho_EN',                None,                    None,                 None),
('TenKho_RU',               'dm_khoduoc',               'TenKho_RU',                None,                    None,                 None),
]


DIM_NhaCungCap=[
('KhoDuoc_Key',               None,               None,                None,                    None,                 None),
('NhaCungCap_Id',               'DM_NhaCungCap',               'NhaCungCap_Id',                None,                    None,                 None),
('MaNhaCungCap',               'DM_NhaCungCap',               'MaNhaCungCap',                None,                    None,                 None),
('TenNhaCungCap',               'DM_NhaCungCap',               'TenNhaCungCap',                None,                    None,                 None),
('TenNhaCungCap_En',               'DM_NhaCungCap',               'TenNhaCungCap_En',                None,                    None,                 None),
('TenNhaCungCap_Ru',               'DM_NhaCungCap',               'TenNhaCungCap_Ru',                None,                    None,                 None),
('DiaChi',               'DM_NhaCungCap',               'DiaChi',                None,                    None,                 None),
('DienThoai',               'DM_NhaCungCap',               'DienThoai',                None,                    None,                 None),
('Fax',               'DM_NhaCungCap',               'Fax',                None,                    None,                 None),
('Email',               'DM_NhaCungCap',               'Email',                None,                    None,                 None),
('MaSoThue',               'DM_NhaCungCap',               'MaSoThue',                None,                    None,                 None),
('GiamDoc',               'DM_NhaCungCap',               'GiamDoc',                None,                    None,                 None),
('NguoiLienHe',               'DM_NhaCungCap',               'NguoiLienHe',                None,                    None,                 None),
('NuocNgoai',               'DM_NhaCungCap',               'NuocNgoai',                None,                    None,                 None),
('NhaNuoc',               'DM_NhaCungCap',               'NhaNuoc',                None,                    None,                 None),
('TamNgung',               'DM_NhaCungCap',               'TamNgung',                None,                    None,                 None),
('TenKhongDau',               'DM_NhaCungCap',               'TenKhongDau',                None,                    None,                 None),
('NgayTao_Key',               'DM_NhaCungCap',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiTao_Id',               'DM_NhaCungCap',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_NhaCungCap',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiCapNhat_Id',               'DM_NhaCungCap',               'NguoiCapNhat_Id',                None,                    None,                 None),
('HeSo',               'DM_NhaCungCap',               'HeSo',                None,                    None,                 None),
('PH_Duoc',               'DM_NhaCungCap',               'PH_Duoc',                None,                    None,                 None),
('PH_NHM',               'DM_NhaCungCap',               'PH_NHM',                None,                    None,                 None),
('PH_TaiSan',               'DM_NhaCungCap',               'PH_TaiSan',                None,                    None,                 None),
('LoaiHinhCongTy',               'DM_NhaCungCap',               'LoaiHinhCongTy_Id',                None,                    None,                 None),
('Intercompany',               'DM_NhaCungCap',               'Intercompany',                None,                    None,                 None),
('tentat',               'DM_NhaCungCap',               'tentat',                None,                    None,                 None),
('idx',               'DM_NhaCungCap',               'idx',                None,                    None,                 None),
('TrangThai',               'DM_NhaCungCap',               'TrangThai',                None,                    None,                 None),
('DonVi',               'DM_NhaCungCap',               'DonVi',                None,                    None,                 None),
]


DIM_CoSoThuoc=[
('CoSoThuoc_Key',               'DM_CoSoThuoc',               None,                None,                    None,                 None),
('CoSoThuoc_Id',               'DM_CoSoThuoc',               'CoSoThuoc_Id',                None,                    None,                 None),
('KhoDuoc_Key',               'DM_CoSoThuoc',               'KhoDuoc_Id',                'DIM_KhoDuoc',                    'KhoDuoc_Key',                 'KhoDuoc_Id'),
('Duoc_Key',               'DM_CoSoThuoc',               'Duoc_Id',                'DIM_Duoc',                    'Duoc_Key',                 'Duoc_Id'),
('SoLuongMin',               'DM_CoSoThuoc',               'SoLuongMin',                None,                    None,                 None),
('SoLuongMax',               'DM_CoSoThuoc',               'SoLuongMax',                None,                    None,                 None),
('TamNgung',               'DM_CoSoThuoc',               'TamNgung',                None,                    None,                 None),
('NgayTao_Key',               'DM_CoSoThuoc',               'NgayTao',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiTao_Id',               'DM_CoSoThuoc',               'NguoiTao_Id',                None,                    None,                 None),
('NgayCapNhat_Key',               'DM_CoSoThuoc',               'NgayCapNhat',                'DIM_Date',                    'Date_Key',                 'Ngay'),
('NguoiCapNhat_Id',               'DM_CoSoThuoc',               'NguoiCapNhat_Id',                None,                    None,                 None),
]


